# Generated by Django 5.1 on 2024-10-26 01:40

import timezone_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField()),
                ('ename', models.CharField(max_length=35)),
                ('esal', models.CharField(max_length=35)),
                ('eadd', models.TextField()),
                ('edate', models.DateField(auto_now_add=True)),
                ('timezone', timezone_field.fields.TimeZoneField(default='utc')),
            ],
        ),
    ]
