# Generated by Django 5.1 on 2024-10-20 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=30)),
                ('salary', models.IntegerField()),
                ('mobile', models.BigIntegerField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
