# Generated by Django 5.1 on 2024-09-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField(max_length=25)),
                ('ename', models.CharField(max_length=35)),
                ('esal', models.FloatField(max_length=30)),
                ('eaddr', models.CharField(max_length=25)),
            ],
        ),
    ]
