# Generated by Django 5.1 on 2024-09-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='eno',
            field=models.IntegerField(),
        ),
    ]
